server:
  port: 9527

spring:
  application:
    name: microservicedemo-zuul-gateway

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


# 测试的访问地址：http://localhost:9527/java3y/mydept/dept/list

zuul:
  #ignored-services: microservicedemo-dept
  prefix: /zbin   #域名前缀
  ignored-services: "*"   #忽略真实微服务名称
  routes:
    mydept.serviceId: microservicedemo-dept   #将真实微服务地址替换成自定义的地址
    mydept.path: /mydept/**

info:
  app.name: zbin-microcloud
  company.name: www.zbin.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

